- name: Install mysql
  apt: name={{item}} state=present
  with_items:
    - mysql-server-5.6
    - python-mysqldb

- name: Create databse
  mysql_db:
    name: "{{database.name}}"
    encoding: utf8
    collation: utf8_unicode_ci
    state: present

- mysql_user:
    name: "{{database.owner}}"
    password: "{{database.password}}"
    priv: '*.*:ALL'
    state: present