#php5 dependancies
- name: Install py2 psycopg2
  when: vagrantbox.basebox == 'ubuntu/trusty64'
  apt: name=python-psycopg2 state=present

#php7 dependancies
- name: Install py3 psycopg2
  when: vagrantbox.basebox == 'ubuntu/xenial64'
  apt: name=python3-psycopg2 state=present

- name: Install postgres
  when: database.type == 'pgsql'
  apt: name={{item}} state=present
  with_items:
    - postgresql
    - libpq-dev

- name: insert/update postgresql conf
  when:
      - database.tuning
      - vagrantbox.basebox == 'ubuntu/trusty64'
  blockinfile:
    block: "{{ lookup('file', 'psql-conf-settings.conf') }}"
    dest: "/etc/postgresql/9.3/main/postgresql.conf"
  notify: Reload postgres

- name: insert/update postgresql conf
  when:
      - database.tuning
      - vagrantbox.basebox == 'ubuntu/xenial64'
  blockinfile:
    block: "{{ lookup('file', 'psql-conf-settings.conf') }}"
    dest: "/etc/postgresql/9.5/main/postgresql.conf"
  notify: Reload postgres

- name: Create databse
  become_user: postgres
  postgresql_db:
    name: "{{database.name}}"
- name: Give user DB access
  become_user: postgres
  postgresql_user:
    db: "{{database.name}}"
    name: "{{database.owner}}"
    password: "{{database.password}}"
    priv: all