#php5 dependancies
- when: boxenvironment.base == 'ubuntu/trusty64'
  name: install py2 psycopg2
  apt: name=python-psycopg2 state=present
- when: boxenvironment.base == 'ubuntu/trusty64'
  name: install php5-pgsql
  apt: name=php5-pgsql state=present
  notify: reload apache

#php7 dependancies
- when: boxenvironment.base == 'ubuntu/xenial64'
  name: install py3 psycopg2
  apt: name=python3-psycopg2 state=present
  notify: reload apache

- when: boxenvironment.base == 'ubuntu/xenial64'
  name: install php7.0-pgsql
  apt: name=php7.0-pgsql state=present
  notify: reload apache


- name: install postgres
  when: database.type == 'pgsql'
  apt: name={{item}} state=present
  with_items:
    - postgresql
    - libpq-dev
- name: ensure database is created
  become_user: postgres
  postgresql_db: 
    name: "{{database.name}}"
- name: ensure user has db access
  become_user: postgres
  postgresql_user: 
    db: "{{database.name}}"
    name: "{{database.owner}}"
    password: "{{database.password}}"
    priv: all