db:
  type: pgsql
  name: moodle
  user: moodleuser
  pass: yourpassword

wwwroot:
    hostpath: ./wwwroot #relative to vagrant folder / or full path
    vmpath: /var/www/wwwroot #full path
    git:
        url: git@github.com:moodle/moodle.git
        branch: MOODLE_31_STABLE

sitedata:
    hostpath: ./sitedata #relative to vagrant folder / or full path
    vmpath: /var/www/sitedata #full path
