db:
  type: pgsql #pgsql or mysql
  name: moodle
  user: moodleuser
  pass: yourpassword

siteroot:
  hostpath: siteroot #relative to vagrant folder
  vmpath: /var/www/siteroot #full path
  git:
    url: git@github.com:moodle/moodle.git
    branch: MOODLE_31_STABLE

site:
  name:
    full: moodle
    short: moodle
  admin:
    user: admin
    pass: password
    email: notanemail@notmail.com

sitedata:
  hostpath: sitedata #relative to vagrant folder
  vmpath: /var/www/sitedata #full path

virtualbox:
  memory: 4096 # in mb
  cores: 2
  name: vagrant-test-box
