---
- name: bigplay
  hosts: all
  become: yes
  become_method: sudo
  handlers: 
    - name: reload apache
      service: name=apache2 state=reloaded
  tasks:
    - name: get config variables
      include_vars:
        file: config.yml
        name: config
    - name: ensure apt cache is up to date
      apt: update_cache=yes
    - name: install apache
      apt: name=apache2 state=present
    - name: install apache-php libs
      apt: name=libapache2-mod-php5 state=present
      notify: reload apache
    - name: install php5-pgsql
      apt: name=php5-pgsql state=present
      notify: reload apache
    - name: install postgres
      when: config.database.type == 'pgsql'
      apt: name={{item}} state=present
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
    - name: ensure database is created
      become_user: postgres
      postgresql_db: 
        name: "{{config.database.name}}"
    - name: ensure user has db access
      become_user: postgres
      postgresql_user: 
        db: "{{config.database.name}}"
        name: "{{config.database.owner}}"
        password: "{{config.database.password}}"
        priv: all
    - name: template moodle config
      template:
        src: moodleconfig.j2
        dest: "{{config.siteroot.vmpath}}/config.php"
    - name: Create sitedata
      file: 
        path: /var/www/sitedata
        state: directory 
        owner: www-data 
        group: www-data 
        mode: 0777
    - name: Copy across new virtual host
      template:
        src: virtual-hosts.conf.j2
        dest: /etc/apache2/sites-available/vagrant.conf
      notify: reload apache
    - name: Remove default virtual host
      file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: reload apache
    - name: Enable new vagrant virtual host
      file:
        src: /etc/apache2/sites-available/vagrant.conf
        dest: /etc/apache2/sites-enabled/vagrant.conf
        state: link
      notify: reload apache