- name: Copy utils folder over
  copy:
    src: "utils"
    dest: "/"
    mode: 0777

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install Git
  apt: name=git state=present

- name: Download Moosh
  git:
    repo: 'git://github.com/tmuras/moosh.git'
    dest: /moosh

- name: Install Moosh
  composer:
    command: install
    working_dir: /moosh

- name: Link Moosh Executable
  file:
    src: /moosh/moosh.php
    dest: /usr/local/bin/moosh
    state: link



