- name: Create sitedata
  file:
    path: /var/www/sitedata
    state: directory
    owner: www-data
    group: www-data
    mode: 0777
- name: Create phpunit sitedata
  file:
    path: /var/www/phpu_sitedata
    state: directory
    owner: www-data
    group: www-data
    mode: 0777
- name: template moodle config
  template:
    src: ../templates/moodle.conf.j2
    dest: "{{siteroot.vmpath}}/config.php"
- name: Install moodle db
  command: php {{siteroot.vmpath}}/admin/cli/install_database.php --agree-license  --adminuser={{moodle.adminuser}} --adminpass={{moodle.adminpassword}} --adminemail={{moodle.adminemail}}
  ignore_errors: yes