- name: Copy utilities over
  when: devtools.utils
  include: utils.yml
- name: Install moosh
  when: devtools.moosh
  include: moosh.yml
- name: Install xdebug
  when: devtools.xdebug
  include: xdebug.yml
- name: Install profiling
  when: devtools.profiling
  include: profiling.yml
- name: Install phpunit
  when: devtools.phpunit.enabled
  include: phpunit.yml


