- name: Install php5 xdebug
  apt: name=php5-xdebug state=present
  notify: Reload Apache

- name: Copy xdebug.ini over
  copy:
    src: "xdebug.ini"
    dest: "/etc/php5/mods-available/xdebug.ini"
  when: vagrantbox.basebox == 'ubuntu/trusty64'
  notify: Reload Apache




