- name: Install php5 xdebug
  when: vagrantbox.basebox == 'ubuntu/trusty64'
  apt: name=php5-xdebug state=present
  notify: Reload apache
- name: Copy php5 xdebug.ini over
  when: vagrantbox.basebox == 'ubuntu/trusty64'
  copy:
    src: "xdebug.ini"
    dest: "/etc/php5/mods-available/xdebug.ini"
  notify: Reload apache




