---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Set Python3 Interpreter
      set_fact:
        ansible_python_interpreter: '/usr/bin/python3'
      when: vagrantbox.basebox == 'ubuntu/xenial64'
    - name: Gathering facts
      setup:
    - name: Include remote ip
      include_vars:
        file: ./remoteip.yml
    - name: Check last apt-cache update
      stat: path=/var/cache/apt
      register: apt_cache_stat
    - name: Update apt-cache
      apt: update_cache=yes
      when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12
  roles:
      - database
      - webserver
      - devtools





