---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Set Python3 Interpreter
      set_fact:
        ansible_python_interpreter: '/usr/bin/python3'
      when: vagrantbox.basebox == 'ubuntu/xenial64'
    - name: Gathering facts
      setup:
    - name: Include remote ip
      include_vars:
        file: ./remoteip.yml
    - name: Update apt-cache
      apt: 
        update_cache: yes 
        cache_valid_time: 3600
  roles:
      - database
      - webserver
      - devtools





