---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Set python3 as interpreter
      include_vars:
        ansible_python_interpreter: /usr/bin/python3
      when: boxenvironment.base == 'ubuntu/xenial64'
    - name: Include remote ip
      include_vars:
        file: ./remoteip.yml
    - name: ensure apt cache is up to date
      apt: update_cache=yes
  tasks:
    - name: Copy utils folder over
      copy:
        src: "../utils"
        dest: "/home/vagrant"
        mode: 0777
        owner: vagrant
        group: vagrant
  roles:
      - webserver
      - database





