---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Set Python3 Interpreter
      set_fact:
        ansible_python_interpreter: '/usr/bin/python3'
      when: vagrantbox.basebox == 'ubuntu/xenial64'
    - name: Include remote ip
      include_vars:
        file: ./remoteip.yml
    - name: ensure apt cache is up to date
      apt: update_cache=yes
  roles:
      - database
      - webserver
      - devtools





