- name: Template moodle config
  template:
    src: ../templates/moodle.conf.j2
    dest: "{{webserver.siteroot.vmpath}}/config.php"
- name: Install moodle db
  command: sudo -u www-data php {{webserver.siteroot.vmpath}}/admin/cli/install_database.php --agree-license  --adminuser={{webserver.moodle.adminuser}} --adminpass={{webserver.moodle.adminpassword}} --adminemail={{webserver.moodle.adminemail}}
  ignore_errors: yes