- name: Install pip
  apt: name=python-pip
  when: vagrantbox.basebox == 'ubuntu/trusty64'

- name: Install pip packages
  pip: name={{item}} state=present
  with_items:
   - urllib3
   - pyopenssl
   - ndg-httpsclient
   - pyasn1
  when: vagrantbox.basebox == 'ubuntu/trusty64'

- name: Import the Nodesource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add repo for Nodesource
  apt_repository:
      repo: "deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main"
      update_cache: yes
      state: present

- name: Install nodejs + npm
  apt: name=nodejs
